spring:
  application:
    name: file-processing-app
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  region: eu-central-1
  s3:
    bucket-name: file-processor-dev-136004864964-files
  sqs:
    queue-url: https://sqs.eu-central-1.amazonaws.com/136004864964/file-processor-dev-queue